# General SonarQube configuration
sonar.projectKey=MovieDesc
sonar.projectName=MovieDesc
sonar.projectVersion=1.0

# Local SonarQube instance
sonar.host.url=http://localhost:9000
sonar.login=sqa_1b3eec0202eacc558d7ee7066a29c6b85b803ed8

# Source directories
sonar.sources=backend,frontend

# Encoding
sonar.sourceEncoding=UTF-8

# Ignore virtual environment, cache, and media
sonar.exclusions=env/**,__pycache__/**,**/*.log,**/*.mp3,**/data/**

# Optional: Python version (not required, but helpful for display)
sonar.python.version=3.12.7
